[package]
edition.workspace = true
license.workspace = true
name = "compostbin-core"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
apple-container.workspace = true
serde.workspace = true
toml.workspace = true

[dev-dependencies]
apple-container = { workspace = true, features = ["fake"] }
tempfile.workspace = true

[features]
strict = []
