[package]
edition.workspace = true
license.workspace = true
name = "compostbin-core"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
compostbin-engine.workspace = true
libc.workspace = true
serde.workspace = true
toml.workspace = true

[dev-dependencies]
compostbin-engine = { workspace = true, features = ["fake"] }
tempfile.workspace = true

[features]
strict = []
