[package]
edition.workspace = true
license.workspace = true
name = "compostbin-test"
publish = false
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dev-dependencies]
compostbin-core.workspace = true
tempfile.workspace = true
toml.workspace = true

[features]
strict = []
