[package]
edition.workspace = true
license.workspace = true
name = "compostbin-test"
publish = false
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
compostbin-core.workspace = true
tempfile.workspace = true
toml.workspace = true

[features]
# Tests in this crate are integration. Enable `--features integration`
# to run them.
integration = []
strict = []
