[package]
edition.workspace = true
license.workspace = true
name = "compostbin-engine"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
containerization-framework.workspace = true
getrandom.workspace = true
libc.workspace = true
sha2.workspace = true

[dev-dependencies]
tempfile.workspace = true

[features]
fake = []      # Expose RecordingEngine to other crates' tests.
strict = []
