[package]
build = "build.rs"
edition.workspace = true
license.workspace = true
name = "containerization-framework-bridge"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
compostbin-engine.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
libc.workspace = true
serde.workspace = true
serde_json.workspace = true
swift-bridge.workspace = true

[target.'cfg(target_os = "macos")'.build-dependencies]
swift-bridge-build.workspace = true

[dev-dependencies]
tempfile.workspace = true

[features]
strict = []
